/**
 * 元数据文件列表
 * 分为 core 和 flex 两种类型
 */
export const metadataFiles = {
  core: [
    'andy_clothes_01_C.json',
    'andy_clothes_010_N.json',
    'andy_clothes_011_R.json',
    'andy_clothes_012_SR_WAGMI War Set.json',
    'andy_clothes_013_R.json',
    'andy_clothes_014_RR.json',
    'andy_clothes_015_RR.json',
    'andy_clothes_016_SSR_Mint Day Set.json',
    'andy_clothes_017_SSR_Joker Set.json',
    'andy_clothes_02_C.json',
    'andy_clothes_03_N.json',
    'andy_clothes_04_SR_Locked Liquidity Set.json',
    'andy_clothes_05_N.json',
    'andy_clothes_06_N.json',
    'andy_clothes_07_C.json',
    'andy_clothes_08_C.json',
    'andy_clothes_09_R.json',
    'andy_headwears_01_C.json',
    'andy_headwears_010_N.json',
    'andy_headwears_011_N.json',
    'andy_headwears_012_R.json',
    'andy_headwears_013_R.json',
    'andy_headwears_014_N.json',
    'andy_headwears_015_R.json',
    'andy_headwears_016_R.json',
    'andy_headwears_017_RR.json',
    'andy_headwears_018_RR.json',
    'andy_headwears_019_RR.json',
    'andy_headwears_02_N.json',
    'andy_headwears_020_SR_Mint Day Set.json',
    'andy_headwears_021_SR_Joker Set.json',
    'andy_headwears_03_SSR_WAGMI War Set.json',
    'andy_headwears_04_SSR_Locked Liquidity Set.json',
    'andy_headwears_05_C.json',
    'andy_headwears_06_C.json',
    'andy_headwears_07_N.json',
    'andy_headwears_08_C.json',
    'andy_headwears_09_C.json',
    'danny_clothes_01_C.json',
    'danny_clothes_010_N.json',
    'danny_clothes_011_R.json',
    'danny_clothes_012_SR_WAGMI War Set.json',
    'danny_clothes_013_R.json',
    'danny_clothes_014_RR.json',
    'danny_clothes_015_RR.json',
    'danny_clothes_016_SSR_Down Bad Set.json',
    'danny_clothes_017_SSR_Muay Thai Set.json',
    'danny_clothes_02_C.json',
    'danny_clothes_03_N.json',
    'danny_clothes_04_SR_Locked Liquidity Set.json',
    'danny_clothes_05_N.json',
    'danny_clothes_06_N.json',
    'danny_clothes_07_C.json',
    'danny_clothes_08_C.json',
    'danny_clothes_09_R.json',
    'danny_headwears_01_C.json',
    'danny_headwears_010_R.json',
    'danny_headwears_011_R.json',
    'danny_headwears_012_RR.json',
    'danny_headwears_013_RR.json',
    'danny_headwears_014_RR.json',
    'danny_headwears_015_C.json',
    'danny_headwears_016_R.json',
    'danny_headwears_017_N.json',
    'danny_headwears_018_N.json',
    'danny_headwears_019_SSR_Locked Liquidity Set.json',
    'danny_headwears_02_N.json',
    'danny_headwears_020_SSR_Down Bad Set.json',
    'danny_headwears_021_SSR_Muay Thai Set.json',
    'danny_headwears_03_SSR_WAGMI War Set.json',
    'danny_headwears_04_C.json',
    'danny_headwears_05_C.json',
    'danny_headwears_06_R.json',
    'danny_headwears_07_C.json',
    'danny_headwears_08_N.json',
    'danny_headwears_09_N.json',
    'ghost_clothes_01_C.json',
    'ghost_clothes_010_N.json',
    'ghost_clothes_011_R.json',
    'ghost_clothes_012_SR_WAGMI Blaster Set.json',
    'ghost_clothes_013_R.json',
    'ghost_clothes_014_RR.json',
    'ghost_clothes_015_RR.json',
    'ghost_clothes_016_SSR_Pre-Chain Set.json',
    'ghost_clothes_017_SSR_Raijin Set.json',
    'ghost_clothes_02_C.json',
    'ghost_clothes_03_N.json',
    'ghost_clothes_04_C.json',
    'ghost_clothes_05_SR_Locked Liquidity Set.json',
    'ghost_clothes_06_N.json',
    'ghost_clothes_07_N.json',
    'ghost_clothes_08_C.json',
    'ghost_clothes_09_R.json',
    'ghost_headwears_01_C.json',
    'ghost_headwears_010_R.json',
    'ghost_headwears_011_RR.json',
    'ghost_headwears_012_RR.json',
    'ghost_headwears_013_R.json',
    'ghost_headwears_014_R.json',
    'ghost_headwears_015_N.json',
    'ghost_headwears_016_R.json',
    'ghost_headwears_017_C.json',
    'ghost_headwears_018_N.json',
    'ghost_headwears_019_C.json',
    'ghost_headwears_02_SSR_WAGMI Blaster Set.json',
    'ghost_headwears_020_SSR_Pre-Chain Set.json',
    'ghost_headwears_021_SSR_Raijin Set.json',
    'ghost_headwears_03_SSR_Locked Liquidity Set.json',
    'ghost_headwears_04_C.json',
    'ghost_headwears_05_N.json',
    'ghost_headwears_06_N.json',
    'ghost_headwears_07_N.json',
    'ghost_headwears_08_C.json',
    'ghost_headwears_09_RR.json',
    'larry_clothes_01_C.json',
    'larry_clothes_010_N.json',
    'larry_clothes_011_R.json',
    'larry_clothes_012_SR_WAGMI War Set.json',
    'larry_clothes_013_R.json',
    'larry_clothes_014_RR.json',
    'larry_clothes_015_RR.json',
    'larry_clothes_016_SSR_FOMO Set.json',
    'larry_clothes_017_SSR_Rug Sniffer Set.json',
    'larry_clothes_02_C.json',
    'larry_clothes_03_N.json',
    'larry_clothes_04_SR_Locked Liquidity Set.json',
    'larry_clothes_05_N.json',
    'larry_clothes_06_N.json',
    'larry_clothes_07_C.json',
    'larry_clothes_08_C.json',
    'larry_clothes_09_R.json',
    'larry_headwears_01_C.json',
    'larry_headwears_010_SSR_WAGMI War Set.json',
    'larry_headwears_011_C.json',
    'larry_headwears_012_N.json',
    'larry_headwears_013_C.json',
    'larry_headwears_014_N.json',
    'larry_headwears_015_N.json',
    'larry_headwears_016_R.json',
    'larry_headwears_017_C.json',
    'larry_headwears_018_C.json',
    'larry_headwears_019_N.json',
    'larry_headwears_02_SSR_Rug Sniffer Set.json',
    'larry_headwears_020_SSR_FOMO Set.json',
    'larry_headwears_021_R.json',
    'larry_headwears_03_SSR_Locked Liquidity Set.json',
    'larry_headwears_04_R.json',
    'larry_headwears_05_N.json',
    'larry_headwears_06_RR.json',
    'larry_headwears_07_RR.json',
    'larry_headwears_08_RR.json',
    'larry_headwears_09_R.json',
    'steve_clothes_01_C.json',
    'steve_clothes_010_N.json',
    'steve_clothes_011_R.json',
    'steve_clothes_012_SR_WAGMI War Set.json',
    'steve_clothes_013_R.json',
    'steve_clothes_014_RR.json',
    'steve_clothes_015_RR.json',
    'steve_clothes_016_SSR_Wontonald Set.json',
    'steve_clothes_017_SSR_Poultry Ponzi Set.json',
    'steve_clothes_02_C.json',
    'steve_clothes_03_N.json',
    'steve_clothes_04_SR_Locked Liquidity Set.json',
    'steve_clothes_05_N.json',
    'steve_clothes_06_N.json',
    'steve_clothes_07_C.json',
    'steve_clothes_08_C.json',
    'steve_clothes_09_R.json',
    'steve_headwears_01_C.json',
    'steve_headwears_010_RR.json',
    'steve_headwears_011_C.json',
    'steve_headwears_012_R.json',
    'steve_headwears_013_N.json',
    'steve_headwears_014_N.json',
    'steve_headwears_015_R.json',
    'steve_headwears_016_C.json',
    'steve_headwears_017_N.json',
    'steve_headwears_018_N.json',
    'steve_headwears_019_R.json',
    'steve_headwears_02_N.json',
    'steve_headwears_020_SSR_Wontonald Set.json',
    'steve_headwears_021_SSR_Poultry Ponzi Set.json',
    'steve_headwears_03_SSR_WAGMI War Set.json',
    'steve_headwears_04_SSR_Locked Liquidity Set.json',
    'steve_headwears_05_C.json',
    'steve_headwears_06_C.json',
    'steve_headwears_07_R.json',
    'steve_headwears_08_RR.json',
    'steve_headwears_09_RR.json',
  ],
  flex: [
    'andy_accessories_013_C.json',
    'andy_accessories_014_C.json',
    'andy_accessories_02_C.json',
    'andy_accessories_09_C.json',
    'andy_opticals_015_C.json',
    'andy_opticals_018_C.json',
    'andy_opticals_019_C.json',
    'andy_opticals_02_C.json',
    'andy_opticals_03_C.json',
    'danny_accessories_013_C.json',
    'danny_accessories_014_C.json',
    'danny_accessories_02_C.json',
    'danny_accessories_09_C.json',
    'danny_opticals_015_C.json',
    'danny_opticals_018_C.json',
    'danny_opticals_019_C.json',
    'danny_opticals_02_C.json',
    'danny_opticals_03_C.json',
    'ghost_accessories_013_C.json',
    'ghost_accessories_014_C.json',
    'ghost_accessories_02_C.json',
    'ghost_accessories_09_C.json',
    'ghost_opticals_015_C.json',
    'ghost_opticals_018_C.json',
    'ghost_opticals_019_C.json',
    'ghost_opticals_02_C.json',
    'ghost_opticals_03_C.json',
    'larry_accessories_013_C.json',
    'larry_accessories_014_C.json',
    'larry_accessories_02_C.json',
    'larry_accessories_09_C.json',
    'larry_opticals_015_C.json',
    'larry_opticals_018_C.json',
    'larry_opticals_019_C.json',
    'larry_opticals_02_C.json',
    'larry_opticals_03_C.json',
    'steve_accessories_013_C.json',
    'steve_accessories_014_C.json',
    'steve_accessories_02_C.json',
    'steve_accessories_09_C.json',
    'steve_opticals_015_C.json',
    'steve_opticals_018_C.json',
    'steve_opticals_019_C.json',
    'steve_opticals_02_C.json',
    'steve_opticals_03_C.json',
    'ghost_weapons_07_C.json',
    'andy_accessories_010_N.json',
    'andy_accessories_012_N.json',
    'andy_accessories_07_N.json',
    'andy_accessories_08_N.json',
    'andy_opticals_012_N.json',
    'andy_opticals_013_N.json',
    'andy_opticals_014_N.json',
    'andy_opticals_016_N.json',
    'andy_opticals_017_N.json',
    'danny_accessories_010_N.json',
    'danny_accessories_012_N.json',
    'danny_accessories_07_N.json',
    'danny_accessories_08_N.json',
    'danny_opticals_012_N.json',
    'danny_opticals_013_N.json',
    'danny_opticals_014_N.json',
    'danny_opticals_016_N.json',
    'danny_opticals_017_N.json',
    'ghost_accessories_010_N.json',
    'ghost_accessories_012_N.json',
    'ghost_accessories_07_N.json',
    'ghost_accessories_08_N.json',
    'ghost_opticals_012_N.json',
    'ghost_opticals_013_N.json',
    'ghost_opticals_014_N.json',
    'ghost_opticals_016_N.json',
    'ghost_opticals_017_N.json',
    'larry_accessories_010_N.json',
    'larry_accessories_012_N.json',
    'larry_accessories_07_N.json',
    'larry_accessories_08_N.json',
    'larry_opticals_012_N.json',
    'larry_opticals_013_N.json',
    'larry_opticals_014_N.json',
    'larry_opticals_016_N.json',
    'larry_opticals_017_N.json',
    'steve_accessories_010_N.json',
    'steve_accessories_012_N.json',
    'steve_accessories_07_N.json',
    'steve_accessories_08_N.json',
    'steve_opticals_012_N.json',
    'steve_opticals_013_N.json',
    'steve_opticals_014_N.json',
    'steve_opticals_016_N.json',
    'steve_opticals_017_N.json',
    'ghost_weapons_03_N.json',
    'andy_accessories_03_R.json',
    'andy_accessories_04_R.json',
    'andy_opticals_010_R.json',
    'andy_opticals_05_R.json',
    'andy_opticals_07_R.json',
    'andy_opticals_08_R.json',
    'andy_opticals_09_R.json',
    'danny_accessories_03_R.json',
    'danny_accessories_04_R.json',
    'danny_opticals_010_R.json',
    'danny_opticals_05_R.json',
    'danny_opticals_08_R.json',
    'danny_opticals_09_R.json',
    'ghost_accessories_03_R.json',
    'ghost_accessories_04_R.json',
    'ghost_opticals_010_R.json',
    'ghost_opticals_05_R.json',
    'ghost_opticals_08_R.json',
    'ghost_opticals_09_R.json',
    'larry_accessories_03_R.json',
    'larry_accessories_04_R.json',
    'larry_opticals_010_R.json',
    'larry_opticals_05_R.json',
    'larry_opticals_08_R.json',
    'larry_opticals_09_R.json',
    'steve_accessories_03_R.json',
    'steve_accessories_04_R.json',
    'steve_opticals_010_R.json',
    'steve_opticals_05_R.json',
    'steve_opticals_08_R.json',
    'steve_opticals_09_R.json',
    'ghost_weapons_04_R.json',
    'andy_accessories_011_RR.json',
    'andy_accessories_06_RR.json',
    'andy_opticals_01_RR.json',
    'andy_opticals_06_RR.json',
    'danny_accessories_011_RR.json',
    'danny_accessories_06_RR.json',
    'danny_opticals_01_RR.json',
    'danny_opticals_06_RR.json',
    'danny_opticals_07_RR.json',
    'ghost_accessories_011_RR.json',
    'ghost_accessories_06_RR.json',
    'ghost_opticals_01_RR.json',
    'ghost_opticals_06_RR.json',
    'ghost_opticals_07_RR.json',
    'larry_accessories_011_RR.json',
    'larry_accessories_06_RR.json',
    'larry_opticals_01_RR.json',
    'larry_opticals_06_RR.json',
    'larry_opticals_07_RR.json',
    'steve_accessories_011_RR.json',
    'steve_accessories_06_RR.json',
    'steve_opticals_01_RR.json',
    'steve_opticals_06_RR.json',
    'steve_opticals_07_RR.json',
    'ghost_weapons_05_RR.json',
    'andy_accessories_01_SR_Locked Liquidity Set.json',
    'andy_accessories_05_SR_WAGMI War Set.json',
    'andy_opticals_020_SR_Mint Day Set.json',
    'andy_opticals_021_SR_Joker Set.json',
    'danny_accessories_01_SR_Locked Liquidity Set.json',
    'danny_accessories_05_SR_WAGMI War Set.json',
    'ghost_accessories_01_SR_Locked Liquidity Set.json',
    'ghost_accessories_05_SR_WAGMI Blaster Set.json',
    'larry_accessories_01_SR_Locked Liquidity Set.json',
    'larry_accessories_05_SR_WAGMI War Set.json',
    'steve_accessories_01_SR_Locked Liquidity Set.json',
    'steve_accessories_05_SR_WAGMI War Set.json',
    'ghost_weapons_02_SR_Locked Liquidity Set.json',
    'ghost_weapons_06_SR_WAGMI Blaster Set.json',
    'andy_accessories_015_SSR_Joker Set.json',
    'andy_accessories_016_SSR_Mint Day Set.json',
    'andy_opticals_011_SSR_WAGMI War Set.json',
    'andy_opticals_04_SSR_Locked Liquidity Set.json',
    'danny_accessories_015_SSR_Muay Thai Set.json',
    'danny_accessories_016_SSR_Down Bad Set.json',
    'danny_opticals_011_SSR_WAGMI War Set.json',
    'danny_opticals_020_SSR_Down Bad Set.json',
    'danny_opticals_021_SSR_Muay Thai Set.json',
    'danny_opticals_04_SSR_Locked Liquidity Set.json',
    'ghost_accessories_015_SSR_Raijin Set.json',
    'ghost_accessories_016_SSR_Pre-Chain Set.json',
    'ghost_opticals_011_SSR_WAGMI Blaster Set.json',
    'ghost_opticals_020_SSR_Pre-Chain Set.json',
    'ghost_opticals_021_SSR_Raijin Set.json',
    'ghost_opticals_04_SSR_Locked Liquidity Set.json',
    'larry_accessories_015_SSR_Rug Sniffer Set.json',
    'larry_accessories_016_SSR_FOMO Set.json',
    'larry_opticals_011_SSR_WAGMI War Set.json',
    'larry_opticals_020_SSR_FOMO Set.json',
    'larry_opticals_021_SSR_Rug Sniffer Set.json',
    'larry_opticals_04_SSR_Locked Liquidity Set.json',
    'steve_accessories_015_SSR_Poultry Ponzi Set.json',
    'steve_accessories_016_SSR_Wontonald Set.json',
    'steve_opticals_011_SSR_WAGMI War Set.json',
    'steve_opticals_020_SSR_Poultry Ponzi Set.json',
    'steve_opticals_021_SSR_Wontonald Set.json',
    'steve_opticals_04_SSR_Locked Liquidity Set.json',
    'ghost_weapons_01_SSR_Pre-Chain Set.json',
    'ghost_weapons_08_SSR_Raijin Set.json',
  ],
};

/**
 * 获取元数据文件列表统计信息
 */
export function getMetadataFilesStats() {
  return {
    coreFilesCount: metadataFiles.core.length,
    flexFilesCount: metadataFiles.flex.length,
    totalFilesCount: metadataFiles.core.length + metadataFiles.flex.length,
  };
}
